services:
  web:
    build: .
    ports:
      - "3000:80"
    env_file:
      - .env
    environment:
      - RAILS_ENV=production
    volumes:
      - ./storage:/rails/storage
      - ./db:/rails/db
    restart: unless-stopped

